### ISSUE TITLE
Version 1 beta 4

### ISSUE THREAD

**Issue by adh30** [adh30/BPplus-Reservoir#2]
Version 1 (Beta 4)
- Include estimates of 3-element Windkessel parameters and compliance using Liu's area method as standard.
- include variables that are produced by Sphygmocor.
- include options to fix Pinfinity at zero (or some other pre-specified value)
- improve detection of end-systole and/or flag errors

**Comment by doingnz** [comment]
has there been any progress on this step? especially detection of end-systole and adding variables produced by Sphygmocor?

**Comment by adh30** [comment]
Not yet. My plan was to do this over Christmas but I got COVID so nothing happened. I've pencilled in the 2nd week of April as time when I can focus on coding, so fingers crossed. Thanks for your input.

Regards
Alun

________________________________
